site_name: ML Aide
theme:
  name: material
  features:
    - navigation.sections
nav:
  - index.md
  - 'Getting Started':
    - start/quickstart.md
    - start/environment-setup.md
  - 'Concepts':
    - concepts/core.md
    - concepts/data-structure.md
  - 'Tutorial':
    - tutorial/introduction.md
    - tutorial/create-project.md
    - tutorial/data-preparation.md
    - tutorial/model-training.md
    - tutorial/model-evaluation.md
    - tutorial/productionize-model.md
  - 'API Reference':
    - api-reference/python-sdk.md
    - api-reference/rest-api.md
extra_css:
  - css/material-enhancements.css
markdown_extensions:
  - attr_list
plugins:
  - render_swagger
  - mkdocstrings:
      watch:
        - ./../../core/python-sdk/src
